In [7]:
import pandas as pd

df = pd.read_csv(
    filepath_or_buffer='/home/cassandra/Lin_Project/meta_data.csv', 
    header=None, 
    sep=',')

df = df.transpose()
df.columns=['GH1', 'GH3', 'GH5','GH9','GH44','GH48','GH10','GH11' ,'GH39','GH43', 'GH67', 'GH16', 'GH31', 'GH2', 'GH26', 'GH36', 'GH88']

df

GH1  GH3  GH5  GH9  GH44  GH48  GH10  GH11  GH39  GH43  GH67  GH16  GH31  \
0    26   67   42   21     7     0    20     2     6    77     5    34    37   
1    21   44   50   26     4     0    14     1     4    59     4    17    33   
2    24   55   58   21     5     0    20     3     8    64     3    28    37   
3    28   62   64   25     4     0    22     0     7    84     5    29    52   
4    52  103   65   31    10     0    27     1     8   128     8    45    70   
5    19   36   12   12     1     1    14     2     1    26     2     2    15   
6    39   68   41   23     9     0    13     1     6    65     5    29    46   
7    13   51   55   27    10     0    19     2    10    80     6    27    33   
8    20  127   74   45     4     0    36     4     5    91     6    35    60   
9    12   54   23   18     1     0    12     7     7    53     5    15    44   
10   20   63   48   38     4     0    31    11     4    48     7    21    38   
11    4    6    5    0     0     0     0     0     0     4     0     1     5   
12   14   80   53   26     2     0    27    11     4    79     4    35    26   
13   27  115  103   54     7     2    37     7     6   112     5    47    41   
14   37   81   27   12     3     0    21    10     7    60     5    17    69   
15    6   19    3    0     0     0     4     0     0     4     0     9    15   
16  365  476  169   95     0     0   128    50    15   239    21   241   428   
17   93  348   57   10     0     0    17     0    22    33     9   185    73   
18  113  560   75    4     0     0    21     0    13   118    10   181    98   
19  222  252   64   22     0     0    29     0     6    35     1   118    59   
20  272  320  102   36    18     0    45     0    20    70     4    45   198   

    GH2  GH26  GH36  GH88  
0    63    10    21    34  
1    45    21    21    18  
2    55    24    14    18  
3    42    20    33    16  
4   109    30    39    55  
5    15     6    12     5  
6    63    12    26    40  
7    49    29    21    31  
8    76    21    54    23  
9    28     5    14    14  
10   43    14    27    26  
11    1     1     1     0  
12   53    21    21    15  
13  110    39    39    39  
14   48     3    27    30  
15    4     0     0     1  
16  253    47   129   180  
17   50     1    35    17  
18   58     2    24    27  
19   84     2     0    44  
20   85    22     0    41

In [16]:
X = df.ix[:,0:17].values
# y = df.ix[:,16].values
print(X)

[[ 26  67  42  21   7   0  20   2   6  77   5  34  37  63  10  21  34]
 [ 21  44  50  26   4   0  14   1   4  59   4  17  33  45  21  21  18]
 [ 24  55  58  21   5   0  20   3   8  64   3  28  37  55  24  14  18]
 [ 28  62  64  25   4   0  22   0   7  84   5  29  52  42  20  33  16]
 [ 52 103  65  31  10   0  27   1   8 128   8  45  70 109  30  39  55]
 [ 19  36  12  12   1   1  14   2   1  26   2   2  15  15   6  12   5]
 [ 39  68  41  23   9   0  13   1   6  65   5  29  46  63  12  26  40]
 [ 13  51  55  27  10   0  19   2  10  80   6  27  33  49  29  21  31]
 [ 20 127  74  45   4   0  36   4   5  91   6  35  60  76  21  54  23]
 [ 12  54  23  18   1   0  12   7   7  53   5  15  44  28   5  14  14]
 [ 20  63  48  38   4   0  31  11   4  48   7  21  38  43  14  27  26]
 [  4   6   5   0   0   0   0   0   0   4   0   1   5   1   1   1   0]
 [ 14  80  53  26   2   0  27  11   4  79   4  35  26  53  21  21  15]
 [ 27 115 103  54   7   2  37   7   6 112   5  47  41 110  39  39  39]
 [ 37 

In [17]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
print(X_std)

[[ -4.39361114e-01  -4.95418655e-01  -4.03173136e-01  -2.44252105e-01
    6.10492494e-01  -3.06186218e-01  -2.61228802e-01  -3.12936880e-01
   -2.78801350e-01   8.50403906e-02  -1.10607018e-01  -3.26609911e-01
   -3.74771108e-01  -1.03000228e-02  -4.37147592e-01  -2.07792004e-01
    5.30018481e-02]
 [ -4.91725379e-01  -6.46866257e-01  -1.83260516e-01   0.00000000e+00
   -5.26286633e-02  -3.06186218e-01  -5.01483028e-01  -4.06817944e-01
   -6.33639432e-01  -2.80246742e-01  -3.42881755e-01  -5.87459438e-01
   -4.19743641e-01  -3.64246261e-01   4.04361523e-01  -2.07792004e-01
   -3.92213676e-01]
 [ -4.60306820e-01  -5.74434795e-01   3.66521033e-02  -2.44252105e-01
    1.68411723e-01  -3.06186218e-01  -2.61228802e-01  -2.19055816e-01
    7.60367318e-02  -1.78778094e-01  -5.75156493e-01  -4.18674450e-01
   -3.74771108e-01  -1.67609462e-01   6.33864009e-01  -4.68864010e-01
   -3.92213676e-01]
 [ -4.18415409e-01  -5.28342047e-01   2.01586568e-01  -4.88504210e-02
   -5.26286633e-02  -3.0618621

In [19]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
print(mean_vec)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

[ -2.11471052e-17  -5.28677631e-17   7.40148683e-17   1.32169408e-17
  -4.22942105e-17   5.28677631e-18  -1.05735526e-16   0.00000000e+00
   6.34413157e-17   1.65211760e-17   4.75809868e-17  -3.70074342e-17
   4.22942105e-17  -4.49375986e-17   2.11471052e-17  -1.05735526e-17
  -4.49375986e-17]
Covariance matrix 
[[  1.05000000e+00   8.14695155e-01   7.92755318e-01   5.92359850e-01
    1.00263744e-01  -1.46864259e-01   8.28200825e-01   5.91707695e-01
    6.61995341e-01   5.76058709e-01   6.05283613e-01   7.67303478e-01
    9.26911704e-01   7.93122192e-01   3.22704634e-01   4.89466418e-01
    8.16538072e-01]
 [  8.14695155e-01   1.05000000e+00   7.12258476e-01   3.29818499e-01
   -1.10703104e-01  -1.13407749e-01   6.06542595e-01   3.90419739e-01
    7.85304189e-01   5.73075356e-01   7.03825797e-01   9.60904772e-01
    7.36601562e-01   6.08832179e-01   1.11663291e-01   4.63697725e-01
    5.83594948e-01]
 [  7.92755318e-01   7.12258476e-01   1.05000000e+00   9.05351498e-01
    2.52972305e-

In [20]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[  2.41072865e-01   2.35550700e-01   1.63499057e-01  -1.90496383e-02
    5.63497105e-01  -7.19098265e-02  -9.96974164e-03  -6.36125352e-02
    2.42123159e-02   1.41944082e-01   1.16850284e-01  -3.49130722e-01
    2.21304425e-01  -4.60849974e-02  -3.15320583e-01  -4.74837861e-01
   -1.34462476e-02]
 [  2.10013059e-01   4.15582133e-01   1.13259093e-01   2.68246533e-01
   -3.72599698e-02  -2.38660832e-01   1.39503663e-01   4.04345347e-01
   -2.04730495e-01  -1.44101408e-01   1.28948860e-01   2.63198900e-01
   -3.74841339e-02   3.82537769e-01   3.36739530e-01  -2.17677390e-01
    1.67034198e-04]
 [  2.82740228e-01  -5.45367328e-02   1.89482592e-01   1.42216015e-01
   -7.87536677e-03  -2.63127656e-01  -3.51547290e-01   1.52619419e-01
   -1.34648541e-01  -1.25597038e-02  -1.63186054e-01   5.41125164e-02
   -4.19973683e-01  -4.72441343e-01  -8.86344249e-02  -4.47130686e-04
    4.35313088e-01]
 [  2.62749307e-01  -2.92597301e-01  -6.19012801e-04  -2.17806385e-02
    9.27794965e-

In [21]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [22]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
11.3799203426
2.3408872417
1.62160833622
0.998868175394
0.653464335335
0.279436563775
0.205953450757
0.131155208539
0.098144840241
0.0580854077983
0.036765242965
0.0194492107646
0.00992378096351
0.00817969786234
0.00351860111058
0.00301097116111
0.00162859283928


In [24]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

/usr/lib/python3/dist-packages/matplotlib/font_manager.py:273: UserWarning:

Matplotlib is building the font cache using fc-list. This may take a moment.

/usr/lib/python3/dist-packages/matplotlib/font_manager.py:273: UserWarning:

Matplotlib is building the font cache using fc-list. This may take a moment.



In [30]:
tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = Bar(
        x=['PC %s' %i for i in range(1,18)],
        y=var_exp,
        showlegend=False)

trace2 = Scatter(
        x=['PC %s' %i for i in range(1,18)], 
        y=cum_var_exp,
        name='cumulative explained variance')

data = Data([trace1, trace2])

layout=Layout(
        yaxis=YAxis(title='Explained variance in percent'),
        title='Explained variance by different principal components')

fig = Figure(data=data, layout=layout)
py.iplot(fig)

In [31]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(17,1), 
                      eig_pairs[1][1].reshape(17,1),
                      eig_pairs[2][1].reshape(17,1)))

print('Matrix W:\n', matrix_w)

Matrix W:
 [[  2.41072865e-01   2.35550700e-01   1.63499057e-01]
 [  2.10013059e-01   4.15582133e-01   1.13259093e-01]
 [  2.82740228e-01  -5.45367328e-02   1.89482592e-01]
 [  2.62749307e-01  -2.92597301e-01  -6.19012801e-04]
 [  2.02568286e-02  -2.47534436e-01   7.10205451e-01]
 [  3.02107170e-03  -3.44871164e-01   1.37149977e-02]
 [  2.93680257e-01  -6.73151499e-02  -6.67034404e-02]
 [  2.52362455e-01  -9.74928144e-02  -3.44048100e-01]
 [  1.73879716e-01   3.29426555e-01   4.26963932e-01]
 [  2.75555555e-01  -1.32391601e-01  -1.05528770e-02]
 [  2.74347026e-01   7.54188800e-02  -1.14362405e-01]
 [  2.28696261e-01   3.78396788e-01  -7.80428247e-02]
 [  2.85037685e-01   9.78194133e-02   1.67740925e-02]
 [  2.92959935e-01  -9.19698740e-02   1.48540590e-02]
 [  2.08089927e-01  -4.26654828e-01   1.59869623e-01]
 [  2.66424474e-01  -1.10713803e-01  -2.52521307e-01]
 [  2.88714516e-01  -4.16391031e-02  -7.57083103e-02]]


In [32]:
Y = X_std.dot(matrix_w)
Y

array([[ -9.03331981e-01,  -2.76789246e-01,   2.40613530e-01],
       [ -1.28476584e+00,  -7.43149635e-01,  -1.04710206e-01],
       [ -9.66697534e-01,  -5.51364044e-01,   4.48428456e-01],
       [ -6.06796330e-01,  -4.88639119e-01,   6.72247687e-02],
       [  1.20462915e+00,  -1.16746388e+00,   1.01425047e+00],
       [ -2.87951578e+00,  -7.29600505e-01,  -1.01802352e+00],
       [ -8.74367981e-01,  -4.30249012e-01,   5.98299476e-01],
       [ -4.14327377e-01,  -1.01249578e+00,   1.26560817e+00],
       [  6.21274425e-01,  -9.69209955e-01,  -3.88714113e-01],
       [ -1.80436723e+00,   3.27435698e-01,  -8.32313708e-01],
       [ -5.25046930e-01,  -6.90617270e-01,  -7.12173993e-01],
       [ -4.01686984e+00,   3.71790039e-01,  -1.15627595e+00],
       [ -6.73941405e-01,  -6.51454259e-01,  -7.64410618e-01],
       [  1.60016240e+00,  -3.40183616e+00,   6.12778465e-01],
       [ -1.09659557e+00,   3.58801555e-01,  -7.29262153e-01],
       [ -3.90276863e+00,   4.92146266e-01,  -1.1759941

In [41]:
Y[:,2]

array([  2.40613530e-01,  -1.04710206e-01,   4.48428456e-01,
         6.72247687e-02,   1.01425047e+00,  -1.01802352e+00,
         5.98299476e-01,   1.26560817e+00,  -3.88714113e-01,
        -8.32313708e-01,  -7.12173993e-01,  -1.15627595e+00,
        -7.64410618e-01,   6.12778465e-01,  -7.29262153e-01,
        -1.17599410e+00,  -1.92115551e+00,   3.48340088e-01,
         4.01739169e-03,  -1.25761266e-01,   4.32923431e+00])

In [42]:
import plotly.graph_objs as go

traces = []

trace1 = go.Scatter3d(
    x=Y[:,0],
    y=Y[:,1],
    z=Y[:,2],
    mode='markers')

data = [trace1]

# layout = go.Layout(
#     margin=dict(
#         l=0,
#         r=0,
#         b=0,
#         t=0
#     )
# )
fig = go.Figure(data=data)
py.iplot(fig, filename='simple-3d-scatter')